version: '3'
services:

  twitter-scraper:
    image: hlkchu/twitter-scraper:dev
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    # environment: